/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/city__road-0.gltf -t 
*/

// import * as THREE from "three";
// import React, { useRef } from "react";
// import { useGLTF } from "@react-three/drei";
// import { GLTF } from "three-stdlib";

// type GLTFResult = GLTF & {
//   nodes: {
//     mesh_0: THREE.Mesh;
//   };
//   materials: {};
//   animations: GLTFAction[];
// };

// type ContextType = Record<
//   string,
//   React.ForwardRefExoticComponent<JSX.IntrinsicElements["mesh"]>
// >;

// export function Model(props: JSX.IntrinsicElements["group"]) {
//   const { nodes, materials } = useGLTF("/city__road-0.gltf") as GLTFResult;
//   return (
//     <group {...props} dispose={null}>
//       <mesh geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} />
//     </group>
//   );
// }

// useGLTF.preload("/city__road-0.gltf");
