[world]
kind = "WorldContract"
class_hash = "0x6f38d5d9507c5d9546290e1a27e309efe5a9af3770b6cc1627db4a1b90a7dce"
original_class_hash = "0x6f38d5d9507c5d9546290e1a27e309efe5a9af3770b6cc1627db4a1b90a7dce"
abi = "manifests/dev/deployment/abis/dojo-world.json"
address = "0xc43c124deaa35d813e0eaff065182f30b2a40a9a6102c7894ee9e95ee86321"
transaction_hash = "0x6d3d44bb97a18aba9a2b5dd4f66a7ca14be5aad7b4483262ece9aafab8ddabf"
block_number = 3
seed = "paved"
manifest_name = "dojo-world"

[world.metadata]
profile_name = "dev"
rpc_url = "https://api.cartridge.gg/x/paved-dev/katana"

[base]
kind = "Class"
class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
original_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/dojo-base.json"
tag = "dojo-base"
manifest_name = "dojo-base"

[[contracts]]
kind = "DojoContract"
address = "0x6c3e98d5e018ebb0f1a1c9d98940e1953302aacad01b918dcfa351f560f0b04"
class_hash = "0x18c64172c0b3df5c28c0ca78df3bbe8031de1ee014a7b752818c1675586fe5c"
original_class_hash = "0x18c64172c0b3df5c28c0ca78df3bbe8031de1ee014a7b752818c1675586fe5c"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/paved-Account-32528a5a.json"
reads = []
writes = [
    "paved-Player",
    "paved-Game",
    "paved-Builder",
    "paved-Char",
    "paved-CharPosition",
    "paved-Tile",
    "paved-TilePosition",
    "paved-Tournament",
]
init_calldata = []
tag = "paved-Account"
systems = ["create"]
manifest_name = "paved-Account-32528a5a"

[[contracts]]
kind = "DojoContract"
address = "0xa3fd0009893ef813d823fe1f74aeeba60ca785d3b5ad1fabd68d65b3dc88b1"
class_hash = "0x7c8fa08906a3c828eb9ad157a61c9997757d381b40f201e97b105deff24e84e"
original_class_hash = "0x7c8fa08906a3c828eb9ad157a61c9997757d381b40f201e97b105deff24e84e"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/paved-Daily-190dcfe2.json"
reads = []
writes = [
    "paved-Player",
    "paved-Game",
    "paved-Builder",
    "paved-Char",
    "paved-CharPosition",
    "paved-Tile",
    "paved-TilePosition",
    "paved-Tournament",
]
init_calldata = ["$contract_address:paved-Token"]
tag = "paved-Daily"
systems = [
    "claim",
    "sponsor",
    "discard",
    "surrender",
    "build",
]
manifest_name = "paved-Daily-190dcfe2"

[[contracts]]
kind = "DojoContract"
address = "0x438324fd2763b98515e7bf8667adea25c93bbbfd183f70425d19f3736b3bdc6"
class_hash = "0x330297e6a9a71cdceca444d471055a74a1990216de3b73bd1e8e0b492060c66"
original_class_hash = "0x330297e6a9a71cdceca444d471055a74a1990216de3b73bd1e8e0b492060c66"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/paved-Duel-723c308b.json"
reads = []
writes = [
    "paved-Player",
    "paved-Game",
    "paved-Builder",
    "paved-Char",
    "paved-CharPosition",
    "paved-Tile",
    "paved-TilePosition",
    "paved-Tournament",
]
init_calldata = ["$contract_address:paved-Token"]
tag = "paved-Duel"
systems = [
    "rename",
    "update",
    "join",
    "ready",
    "transfer",
    "leave",
    "kick",
    "delete",
    "start",
    "claim",
    "discard",
    "build",
]
manifest_name = "paved-Duel-723c308b"

[[contracts]]
kind = "DojoContract"
address = "0x31e704ae0558cd3e91d71eebaeb470acb47a6eebc91c2b50347a8dd23f8b6ee"
class_hash = "0x309ff4f51592008074e9aab1dcf52dc56fd4e2555e3551a8bff89a9931ec8f"
original_class_hash = "0x309ff4f51592008074e9aab1dcf52dc56fd4e2555e3551a8bff89a9931ec8f"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/paved-Token-176a6962.json"
reads = []
writes = []
init_calldata = []
tag = "paved-Token"
systems = ["mint"]
manifest_name = "paved-Token-176a6962"

[[contracts]]
kind = "DojoContract"
address = "0x781505ded88b9464f15bae901be530845b269e5635e6e805daf304272ec25ed"
class_hash = "0x281511c2898f8be49cdbcdbfa5c432e4c0031bc352ac675ec481df1af4044e3"
original_class_hash = "0x281511c2898f8be49cdbcdbfa5c432e4c0031bc352ac675ec481df1af4044e3"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/paved-Tutorial-242a6cba.json"
reads = []
writes = [
    "paved-Player",
    "paved-Game",
    "paved-Builder",
    "paved-Char",
    "paved-CharPosition",
    "paved-Tile",
    "paved-TilePosition",
    "paved-Tournament",
]
init_calldata = []
tag = "paved-Tutorial"
systems = [
    "discard",
    "surrender",
    "build",
]
manifest_name = "paved-Tutorial-242a6cba"

[[contracts]]
kind = "DojoContract"
address = "0x7d4b9a1a5a044e97fbf64b320c21f5d1a56f831c949b7e63faf9a8447505567"
class_hash = "0x4be15412c057b4ec6d8671deecd30e1c64b1640131182e24898d982459eaae3"
original_class_hash = "0x4be15412c057b4ec6d8671deecd30e1c64b1640131182e24898d982459eaae3"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/paved-Weekly-3f7fa769.json"
reads = []
writes = [
    "paved-Player",
    "paved-Game",
    "paved-Builder",
    "paved-Char",
    "paved-CharPosition",
    "paved-Tile",
    "paved-TilePosition",
    "paved-Tournament",
]
init_calldata = ["$contract_address:paved-Token"]
tag = "paved-Weekly"
systems = [
    "claim",
    "sponsor",
    "discard",
    "surrender",
    "build",
]
manifest_name = "paved-Weekly-3f7fa769"

[[models]]
kind = "DojoModel"
class_hash = "0x531a5de086dff196f065b57147588d65563af4952a32b78ce0269df0d24408d"
original_class_hash = "0x531a5de086dff196f065b57147588d65563af4952a32b78ce0269df0d24408d"
abi = "manifests/dev/deployment/abis/models/paved-Builder-14d78ed3.json"
tag = "paved-Builder"
qualified_path = "paved::models::index::builder"
manifest_name = "paved-Builder-14d78ed3"

[[models.members]]
name = "game_id"
type = "u32"
key = true

[[models.members]]
name = "player_id"
type = "felt252"
key = true

[[models.members]]
name = "index"
type = "u8"
key = false

[[models.members]]
name = "characters"
type = "u8"
key = false

[[models.members]]
name = "discarded"
type = "u8"
key = false

[[models.members]]
name = "built"
type = "u8"
key = false

[[models.members]]
name = "score"
type = "u32"
key = false

[[models.members]]
name = "tile_id"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x2feaa39db08789fc54ad6596a504fe1eb1a5f5d117493127f6039db9bef7ad8"
original_class_hash = "0x2feaa39db08789fc54ad6596a504fe1eb1a5f5d117493127f6039db9bef7ad8"
abi = "manifests/dev/deployment/abis/models/paved-Char-681e2c82.json"
tag = "paved-Char"
qualified_path = "paved::models::index::char"
manifest_name = "paved-Char-681e2c82"

[[models.members]]
name = "game_id"
type = "u32"
key = true

[[models.members]]
name = "player_id"
type = "felt252"
key = true

[[models.members]]
name = "index"
type = "u8"
key = true

[[models.members]]
name = "tile_id"
type = "u32"
key = false

[[models.members]]
name = "spot"
type = "u8"
key = false

[[models.members]]
name = "weight"
type = "u8"
key = false

[[models.members]]
name = "power"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x54756f3032dab8940835f4804b9a7dc37f32cf08b7f2f5f91415406cf38dea2"
original_class_hash = "0x54756f3032dab8940835f4804b9a7dc37f32cf08b7f2f5f91415406cf38dea2"
abi = "manifests/dev/deployment/abis/models/paved-CharPosition-75ce649a.json"
tag = "paved-CharPosition"
qualified_path = "paved::models::index::char_position"
manifest_name = "paved-CharPosition-75ce649a"

[[models.members]]
name = "game_id"
type = "u32"
key = true

[[models.members]]
name = "tile_id"
type = "u32"
key = true

[[models.members]]
name = "spot"
type = "u8"
key = true

[[models.members]]
name = "player_id"
type = "felt252"
key = false

[[models.members]]
name = "index"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x4060c35b7a34092daea0bcf62155c98bd381a7cf71381a5afdf122a796ab4f7"
original_class_hash = "0x4060c35b7a34092daea0bcf62155c98bd381a7cf71381a5afdf122a796ab4f7"
abi = "manifests/dev/deployment/abis/models/paved-Game-18a55e57.json"
tag = "paved-Game"
qualified_path = "paved::models::index::game"
manifest_name = "paved-Game-18a55e57"

[[models.members]]
name = "id"
type = "u32"
key = true

[[models.members]]
name = "over"
type = "bool"
key = false

[[models.members]]
name = "claimed"
type = "bool"
key = false

[[models.members]]
name = "mode"
type = "u8"
key = false

[[models.members]]
name = "tile_count"
type = "u32"
key = false

[[models.members]]
name = "player_count"
type = "u8"
key = false

[[models.members]]
name = "tournament_id"
type = "u64"
key = false

[[models.members]]
name = "start_time"
type = "u64"
key = false

[[models.members]]
name = "end_time"
type = "u64"
key = false

[[models.members]]
name = "duration"
type = "u64"
key = false

[[models.members]]
name = "tiles"
type = "u128"
key = false

[[models.members]]
name = "players"
type = "u128"
key = false

[[models.members]]
name = "price"
type = "felt252"
key = false

[[models.members]]
name = "prize"
type = "felt252"
key = false

[[models.members]]
name = "name"
type = "felt252"
key = false

[[models.members]]
name = "seed"
type = "felt252"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x17b956d534327c638abb6cfd7a7329c189308459a9562edd581c1349e3c4515"
original_class_hash = "0x17b956d534327c638abb6cfd7a7329c189308459a9562edd581c1349e3c4515"
abi = "manifests/dev/deployment/abis/models/paved-Player-6cc2d65b.json"
tag = "paved-Player"
qualified_path = "paved::models::index::player"
manifest_name = "paved-Player-6cc2d65b"

[[models.members]]
name = "id"
type = "felt252"
key = true

[[models.members]]
name = "name"
type = "felt252"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x4c03ab19f56572ea856fcb457769248776ffa376012e4a5e0a0216c92995a47"
original_class_hash = "0x4c03ab19f56572ea856fcb457769248776ffa376012e4a5e0a0216c92995a47"
abi = "manifests/dev/deployment/abis/models/paved-Tile-1731062d.json"
tag = "paved-Tile"
qualified_path = "paved::models::index::tile"
manifest_name = "paved-Tile-1731062d"

[[models.members]]
name = "game_id"
type = "u32"
key = true

[[models.members]]
name = "id"
type = "u32"
key = true

[[models.members]]
name = "player_id"
type = "felt252"
key = false

[[models.members]]
name = "plan"
type = "u8"
key = false

[[models.members]]
name = "orientation"
type = "u8"
key = false

[[models.members]]
name = "x"
type = "u32"
key = false

[[models.members]]
name = "y"
type = "u32"
key = false

[[models.members]]
name = "occupied_spot"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x35d400c4de200ee037048d9d65b63911910f8f5ff7e0d6aa517490ee04a9326"
original_class_hash = "0x35d400c4de200ee037048d9d65b63911910f8f5ff7e0d6aa517490ee04a9326"
abi = "manifests/dev/deployment/abis/models/paved-TilePosition-d7021627.json"
tag = "paved-TilePosition"
qualified_path = "paved::models::index::tile_position"
manifest_name = "paved-TilePosition-d7021627"

[[models.members]]
name = "game_id"
type = "u32"
key = true

[[models.members]]
name = "x"
type = "u32"
key = true

[[models.members]]
name = "y"
type = "u32"
key = true

[[models.members]]
name = "tile_id"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x25984318d374e572c945fecb7bbed6fafa239384092c2c1811550c1ce26f19d"
original_class_hash = "0x25984318d374e572c945fecb7bbed6fafa239384092c2c1811550c1ce26f19d"
abi = "manifests/dev/deployment/abis/models/paved-Tournament-98c47691.json"
tag = "paved-Tournament"
qualified_path = "paved::models::index::tournament"
manifest_name = "paved-Tournament-98c47691"

[[models.members]]
name = "id"
type = "u64"
key = true

[[models.members]]
name = "prize"
type = "felt252"
key = false

[[models.members]]
name = "top1_player_id"
type = "felt252"
key = false

[[models.members]]
name = "top2_player_id"
type = "felt252"
key = false

[[models.members]]
name = "top3_player_id"
type = "felt252"
key = false

[[models.members]]
name = "top1_score"
type = "u32"
key = false

[[models.members]]
name = "top2_score"
type = "u32"
key = false

[[models.members]]
name = "top3_score"
type = "u32"
key = false

[[models.members]]
name = "top1_claimed"
type = "bool"
key = false

[[models.members]]
name = "top2_claimed"
type = "bool"
key = false

[[models.members]]
name = "top3_claimed"
type = "bool"
key = false
