kind = "DojoModel"
class_hash = "0x17b956d534327c638abb6cfd7a7329c189308459a9562edd581c1349e3c4515"
original_class_hash = "0x17b956d534327c638abb6cfd7a7329c189308459a9562edd581c1349e3c4515"
abi = "manifests/dev/base/abis/models/paved-Player-6cc2d65b.json"
tag = "paved-Player"
qualified_path = "paved::models::index::player"
manifest_name = "paved-Player-6cc2d65b"

[[members]]
name = "id"
type = "felt252"
key = true

[[members]]
name = "name"
type = "felt252"
key = false
