kind = "DojoModel"
class_hash = "0x4060c35b7a34092daea0bcf62155c98bd381a7cf71381a5afdf122a796ab4f7"
original_class_hash = "0x4060c35b7a34092daea0bcf62155c98bd381a7cf71381a5afdf122a796ab4f7"
abi = "manifests/dev/base/abis/models/paved-Game-18a55e57.json"
tag = "paved-Game"
qualified_path = "paved::models::index::game"
manifest_name = "paved-Game-18a55e57"

[[members]]
name = "id"
type = "u32"
key = true

[[members]]
name = "over"
type = "bool"
key = false

[[members]]
name = "claimed"
type = "bool"
key = false

[[members]]
name = "mode"
type = "u8"
key = false

[[members]]
name = "tile_count"
type = "u32"
key = false

[[members]]
name = "player_count"
type = "u8"
key = false

[[members]]
name = "tournament_id"
type = "u64"
key = false

[[members]]
name = "start_time"
type = "u64"
key = false

[[members]]
name = "end_time"
type = "u64"
key = false

[[members]]
name = "duration"
type = "u64"
key = false

[[members]]
name = "tiles"
type = "u128"
key = false

[[members]]
name = "players"
type = "u128"
key = false

[[members]]
name = "price"
type = "felt252"
key = false

[[members]]
name = "prize"
type = "felt252"
key = false

[[members]]
name = "name"
type = "felt252"
key = false

[[members]]
name = "seed"
type = "felt252"
key = false
