[package]
name = "paved"
version = "0.0.0"
edition = "2023_11"

[cairo]
sierra-replace-ids = true

[scripts]
test = "snforge test"

[dependencies]
starknet = "2.20.1"

[[target.starknet-contract]]

[profile.dev.cairo]
unstable-add-statements-functions-debug-info = true
unstable-add-statements-code-locations-debug-info = true
inlining-strategy = "avoid"

[dev-dependencies]
cairo_test = "2.20.1"
snforge_std = "0.64.0"
