tag = "paved-Duel"
writes = [
    "paved-Player",
    "paved-Game",
    "paved-Builder",
    "paved-Char",
    "paved-CharPosition",
    "paved-Tile",
    "paved-TilePosition",
    "paved-Tournament",
]
init_calldata = [
    "0x44e6bcc627e6201ce09f781d1aae44ea4c21c2fdef299e34fce55bef2d02210",
]
