kind = "DojoContract"
class_hash = "0x281511c2898f8be49cdbcdbfa5c432e4c0031bc352ac675ec481df1af4044e3"
original_class_hash = "0x281511c2898f8be49cdbcdbfa5c432e4c0031bc352ac675ec481df1af4044e3"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/paved-Tutorial-242a6cba.json"
reads = []
writes = []
init_calldata = []
tag = "paved-Tutorial"
systems = [
    "discard",
    "surrender",
    "build",
]
manifest_name = "paved-Tutorial-242a6cba"
