kind = "DojoContract"
class_hash = "0x18c64172c0b3df5c28c0ca78df3bbe8031de1ee014a7b752818c1675586fe5c"
original_class_hash = "0x18c64172c0b3df5c28c0ca78df3bbe8031de1ee014a7b752818c1675586fe5c"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/paved-Account-32528a5a.json"
reads = []
writes = []
init_calldata = []
tag = "paved-Account"
systems = ["create"]
manifest_name = "paved-Account-32528a5a"
