kind = "DojoContract"
class_hash = "0x7c8fa08906a3c828eb9ad157a61c9997757d381b40f201e97b105deff24e84e"
original_class_hash = "0x7c8fa08906a3c828eb9ad157a61c9997757d381b40f201e97b105deff24e84e"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/paved-Daily-190dcfe2.json"
reads = []
writes = []
init_calldata = []
tag = "paved-Daily"
systems = [
    "claim",
    "sponsor",
    "discard",
    "surrender",
    "build",
]
manifest_name = "paved-Daily-190dcfe2"
