kind = "DojoContract"
class_hash = "0x4be15412c057b4ec6d8671deecd30e1c64b1640131182e24898d982459eaae3"
original_class_hash = "0x4be15412c057b4ec6d8671deecd30e1c64b1640131182e24898d982459eaae3"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/paved-Weekly-3f7fa769.json"
reads = []
writes = []
init_calldata = []
tag = "paved-Weekly"
systems = [
    "claim",
    "sponsor",
    "discard",
    "surrender",
    "build",
]
manifest_name = "paved-Weekly-3f7fa769"
